server:
  servlet:
    context-path: /
  port: 8080
spring:
  mail:
    host: smtp.qq.com
    username: 390597658@qq.com
    password: zymbtjndogqocbbh
    port: 25
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: lichen
    password: Lichen!0524
    url: jdbc:mysql://zin4ever.top/dictation_db?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  redis:
    sentinel:
      master: mymaster
      nodes: 114.55.101.120:26379
    password: sunnycat
    database: 0
#    sentinel:
#      master: myredis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapping/*Mapper.xml
logging:
  file:
    path: /
    name: dictation.log
